### ISSUE TITLE
Multiple CNAME not works

### ISSUE THREAD

**Issue by quantiti** [lixiangzhong/dnsutil#2]
When I try to use dnsutil to dig some dns with multiple CNAME it seem not works well
E.g neo.microsoft.com
When use dig: 
;; ANSWER SECTION:
neo.microsoft.com.	3512	IN	CNAME	neoportal.azurewebsites.net.
neoportal.azurewebsites.net. 1799 IN	CNAME	waws-prod-bay-075.vip.azurewebsites.windows.net.
waws-prod-bay-075.vip.azurewebsites.windows.net. 299 IN	CNAME waws-prod-bay-075.cloudapp.net.
waws-prod-bay-075.cloudapp.net.	59 IN	A	104.40.3.53

When use dnsutil
dig.SetDNS("8.8.8.8")
a, err := dig.CNAME("neo.microsoft.com")  // dig google.com @8.8.8.8
fmt.Println(a, err)
Result: [neo.microsoft.com.	3599	IN	CNAME	neoportal.azurewebsites.net.] <nil>

**Comment by lixiangzhong** [comment]
```sh
dig cname neo.microsoft.com @8.8.8.8

; <<>> DiG 9.11.3-1-Debian <<>> cname neo.microsoft.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46192
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;neo.microsoft.com.             IN      CNAME

;; ANSWER SECTION:
neo.microsoft.com.      3599    IN      CNAME   neoportal.azurewebsites.net.

;; Query time: 73 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Oct 12 17:14:17 CST 2018
;; MSG SIZE  rcvd: 87
```

return multiple CNAME  Because you didn't bring DNS type.  (default A)

try
```sh
package main

import (
	"github.com/lixiangzhong/dnsutil"
	"github.com/miekg/dns"
	"log"
)

func main() {
	var dig dnsutil.Dig
	dig.SetDNS("8.8.8.8")
	result, err := dig.GetMsg(dns.TypeA, "neo.microsoft.com")
	if err != nil {
		log.Println(err)
		return
	}
	log.Println(result)
}

```
