### ISSUE TITLE
fallback from udp to tcp missing

### ISSUE THREAD

**Issue by MEschenbacher** [lixiangzhong/dnsutil#6]
Hey,

great library. I noticed a detail:

`dig` implements a fallback from `udp` to `tcp` if required. I've seen no direct way to configure this mechanism.

https://godoc.org/github.com/miekg/dns#Client.Exchange documents this fact.

Best Regards,

Max

**Comment by lixiangzhong** [comment]
I have no time to maintain this library recently, welcome PR👍

**Comment by lixiangzhong** [comment]
updated v1.4.0
